### ISSUE TITLE
Ontwerpfase iets uitgebreider

### ISSUE THREAD

**Issue by sannevanseeventer** [iBadr49/server-side-rendering#5]
Probeer meerdere technieken van de ontwerpfase te laten zien. Dus bijvoorbeeld: een wireflow, of een schets van de klikbare onderdelen van je website, zodat je de gedragscriteria die hieronder beschreven staat gedaan hebt. 

Gedragscrireria:
'Je toont aan dat je in de ontwerpfase verschillende methoden en technieken hebt ingezet die ervoor zorgen dat je precies weet wat je moet bouwen'

**Comment by iBadr49** [comment]
Yes dit heb ik tijdje geleden gefixt.
